### PR TITLE
skip 4 failing tests, 3 are tests which failed, then worked and now fail again

### PR DESCRIPTION
**Pull request by jamesfredley**
3 of these were working and were restored on 10/3/24, but are now failing again.  https://github.com/grails/grails-functional-tests/pull/251/files

https://github.com/grails/grails-functional-tests/pull/254 - list of failing tests

**This PR is not needed if we fix the cause identified in the comments below.**

### CODE REVIEW

**Comment by jamesfredley** [comment]
There were two failures after that commit, but the errors were different and appeared to resolve, possibly a stale cached version of grails-async:6.0.0-SNAPSHOT.

https://github.com/grails/grails-core/commit/2edb2e3859833f7cf887568a303717afaa6cefcd is the PR which triggered https://github.com/grails/grails-functional-tests/actions/runs/11311524760 which was the first time we saw these 4 failures, actually 8, but 4 are still failing.

**Comment by matrei** [comment]
Looking at the [test failures](https://ge.grails.org/s/v22rejbiksjda/tests/task/:app1:integrationTest/details/functionaltests.AsyncFunctionalSpec/Test%20async%20response%20rendering%20works?top-execution=1) and timing, I still think this change to `grails-async` (https://github.com/grails/grails-async/commit/e5531e7e8d96d2d3656dd9535121aa8fa893628c) might be a suspect. @codeconsole What do you think?

**Comment by codeconsole** [comment]
@matrei  yeah, could very well be.  It was on my bucket list to test async, but haven't had time to get to it.

**Comment by matrei** [comment]
We are getting `java.lang.NoClassDefFoundError: org/apache/commons/lang/ClassUtils` in this [test](https://ge.grails.org/s/i366fceyqpubg/tests/task/:app1:integrationTest/details/functionaltests.BookFunctionalSpec/Test%20that%20when%20the%20%2FviewBooks%20URL%20is%20hit%20it%20redirects%20to%20the%20book%20list?focused-execution=1&top-execution=1#L157).

So, this is definitively a probably culprit: https://github.com/grails/grails-core/commit/2edb2e3859833f7cf887568a303717afaa6cefcd

**Comment by codeconsole** [comment]
@matrei now that definitely makes sense, but that is originating from the fields plugin. So the field plugin is the one that needs that import.

**Comment by matrei** [comment]
> We are getting java.lang.NoClassDefFoundError: org/apache/commons/lang/ClassUtils in this [test](https://ge.grails.org/s/i366fceyqpubg/tests/task/:app1:integrationTest/details/functionaltests.BookFunctionalSpec/Test%20that%20when%20the%20%2FviewBooks%20URL%20is%20hit%20it%20redirects%20to%20the%20book%20list?focused-execution=1&top-execution=1#L157).
So, this is definitively a probably culprit: https://github.com/grails/grails-core/commit/2edb2e3859833f7cf887568a303717afaa6cefcd

Scratch that, this test is working now.

**Comment by matrei** [comment]
@codeconsole What does it take to make sitemesh layouts work in the test apps in this repo?
https://github.com/grails/grails-functional-tests/blob/b476ac6006e3a123f10bcbb6be5021ff942682db/app1/src/integration-test/groovy/functionaltests/sitemesh/SitemeshLayoutFunctionalSpec.groovy#L12

**Comment by codeconsole** [comment]
> @codeconsole What does it take to make sitemesh layouts work in the test apps in this repo?
> 
> https://github.com/grails/grails-functional-tests/blob/b476ac6006e3a123f10bcbb6be5021ff942682db/app1/src/integration-test/groovy/functionaltests/sitemesh/SitemeshLayoutFunctionalSpec.groovy#L12

Right now you manually have to add the plugin dependency, but it should be me made an api dependency of another dependency. The question is, which one?  I am not sure if gsp should depend on sitemesh.  What is responsible for mapping gsps to the layouts folder?

**Comment by jamesfredley** [comment]
I am merging this so that we have working functional tests to use with https://docs.google.com/document/d/1k5J5ZqUW-ofOMuZJ-eljrg4yqAFHBAhQFa-sY-1EQ5o/edit#heading=h.7j0mm9z5mgub.  I have been using this branch to test the last several changes, include for grails-core.  

The two distinct groups of test failures will be moved to issues.

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-functional-tests/issues/257

**Pull request merged**
