### PR TITLE
Remove test for deprecated/removed Grails Filters

### PR DESCRIPTION
**Pull request by matrei**
Grails Filters support was dropped in Grails 3.2 (see commit f370b49). This test is now ignored to reflect the removal of support and avoid confusion.

### CODE REVIEW

**Comment by matrei** [comment]
Test failure will be resolved by #266

**Comment by jdaugherty** [comment]
Wasn't filters replaced by Interceptors?  Why not just remove the test since there are interceptor tests?

**Review by jdaugherty — APPROVED** [review]
I would opt to remove the test instead.

**Comment by matrei** [comment]
> Wasn't the filters function replaced by Interceptors?

Yes

> Why not just remove the test since there are interceptor tests?

We could do that instead. If there is no value in keeping it? I guess there isn't?
@jamesfredley Any preferences?

**Comment by jamesfredley** [comment]
Let's remove the test.

**Review by jamesfredley — APPROVED** [review]

**Pull request merged**
